version: '3.1'
services:
  stats-server:
    build: stats/stats-server
    container_name: shareit-gateway-image
    restart: always
    ports:
      - "9090:9090"
      - "5006:5006"
    depends_on:
      - server
      - db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ewmstats



  stats-db:
    image: postgres:13.7-alpine
    restart: always
    ports:
      - "6541:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ewmstats
