version: '3.8'
services:
  stats-server:
    build: stats-server/
    container_name: stats-server-image
    restart: always
    ports:
      - "9090:9090"
      - "5005:5005"
    depends_on:
      - db
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

  db:
    image: postgres:13.7-alpine
    restart: always
    ports:
      - "6541:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: stats-server