spring.sql.init.mode: always

spring.config.activate.on-profile: ci,test
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.url: jdbc:postgresql://db:5432/java-explore-with-me
spring.datasource.username: root
spring.datasource.password: root
