server:
  port: 9090

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root

  sql:
    init:
      mode: always
